# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MaxRep' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MaxRep
  pod 'SnapKit'
  pod 'SwiftyJSON'
  pod 'RealmSwift', '3.6.0'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
end
